services:
  linecook-api:
#    image: ghcr.io/johnfodero/linecook:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linecook-api
    ports:
      - "8000:8000"
    environment:
      # Load environment variables from .env file
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - MODEL_ID=${MODEL_ID:-shipping-label-k3hzg/4}
      - CONFIDENCE_THRESH=${CONFIDENCE_THRESH:-0.04}
    env_file:
      - .env
    restart: unless-stopped
    # uncomment when running on a linux host 
    # volumes:
    #   - /var/run/cups/cups.sock:/var/run/cups/cups.sock
    #   - /env/cups:/env/cups:ro
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
